README.md, create_docker_sysext.sh
- create_docker_sysext.sh: Allow to limit sysext to Docker or containerd
With Kubernetes users may want to only ship containerd instead of also
Docker. At the same time it may be handy to layer Docker on top if
needed.
Introduce arguments that allow to limit the build to one of Docker or
containerd.
- create_docker_sysext.sh: Enable containerd.service by default
This is also done in Flatcar for Kubernetes 1.24.
- create_docker_sysext.sh: Add workaround for missing squashfs tool
On Flatcar we don't have mksquashfs but still want to create sysext
images for testing.
Allow to use btrfs or ext4 as alternative format but don't recommend
it.
Serve the images locally after building with `ONLY_DOCKER=1 ./create_docker_sysext.sh 20.10.21 docker` and `ONLY_CONTAINERD=1 ./create_docker_sysext.sh …
=> create_docker_sysext.sh: Allow to limit sysext to Docker or containerd

create_docker_sysext.sh, create_wasmtime_sysext.sh
Even though wasmtime is a single binary (which seems to link to an old enough glibc), it's a good showcase for sysext images because using a Docker container to run wasmtime would add unnecessary overhead when spawning many instances.
```
./create_wasmtime_sysext.sh 4.0.0 flatcar-wasmtime
scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 2222 flatcar-wasmtime.raw  core@127.0.0.1:
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 core@127.0.0.1
sudo mkdir -p /etc/extensions/
sudo mv flatcar-wasmtime.raw /etc/extensions/
sudo systemctl restart systemd-sysext
```
=> Add wasmtime sysext helper

README.md, bake.sh, convert_torcx_image.sh, create_docker_sysext.sh, create_wasmtime_sysext.sh
The code to package the folder in filesystem image was shared. To ease maintenance and adding new features like systemd-repart for GPT images with dm-verity, move it to an own helper. While doing so we can also support the new properties that we added in systemd 252.
You can use the `bake.sh` script also standalone to make an image of a folder you prepared.
Tested wasmtime, docker release, and torcx conversion sysext images for amd64 and arm64, checked on Alpha that the ARCHITECTURE field and OS=_any works.
=> Move sysext image creation to shared helper

README.md
Instances deployed with a custom Docker version shouldn't suddenly get the default one of Flatcar when we ship it as sysext. The docs to opt- out were assuming that they should mask the default sysext from /usr. However, /usr as location for sysext images is removed and we have to enable the Flatcar default sysext through a symlink in /etc. Document that the user should create this symlink to prevent it from popping up through an update.
=> Update instructions to opt-out of a future Flatcar Docker sysext

create_docker_compose_sysext.sh
The standalone docker-compose binary is replaced by a new CLI plugin. This CLI plugin needs to live under /usr, thus we have to use a sysext image.
Add a helper to create a sysext image. While we could also add it by default to the docker sysext script, the separate usage is of more interest because it can be used with Flatcar's default Docker.
Done by following
https://docs.docker.com/compose/install/linux/#install-the-plugin-manually
```
$ ./create_docker_compose_sysext.sh 2.18.1 docker-compose-2.18.1
$ scp -r -C -P 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker-compose-2.18.1.raw      core@127.0.0.1:
$ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 core@127.0.0.1
$ sudo mkdir /etc/extensions
$ sudo mv docker-compose-2.18.1.raw …
```
=> Add docker compose CLI plugin sysext

README.md
CLC is not recommended anymore because it generates Ignition spec v2. Use Butane to generate a Ignition spec v3 config.
Pasted it in `butane` and it didn't complain
=> README: Use Butane instead of CLC

README.md
The systemd-sysupdate components need to be updated either manually or
automatically.
Extend the OS-level sysupdate timer to also cover additional components
and reload the sysext images after an update.
- README: Also disable future inbuilt docker/containerd sysexts
With qemu
=> README: Add sysext update service to Ignition setup

create_docker_compose_sysext.sh, create_docker_sysext.sh, create_wasmtime_sysext.sh
The difference in architecture identifiers from upstream binary releases and what systemd expects in the extension metadata or the update manifest easily causes confusion.
Recommend the use of the systemd identifiers as they will show up in filenames. Map the identifiers internally and try to do the right thing even if a slighly different identifier was called.
The list of systemd identifiers is here https://www.freedesktop.org/software/systemd/man/systemd.unit.html#ConditionArchitecture=
Built the wasmtime image with the default arch (x86-64) and for arm64.
=> Use only systemd arch identifiers for user parameters

.github/workflows/release.yaml, README.md, create_kubernetes_sysext.sh
The publishing was assuming x86-64 as only architecture. Add arm64 as well and while at it provide the .conf sysupdate files for inclusion via HTTP from Ignition.
Made a release with this: https://github.com/flatcar/sysext-bakery/releases/tag/20230901
and tested the Butane config.
=> release: Rework publishing to mark the arch and add sysupdate conf files

create_kubernetes_sysext.sh
Containerd expects cni binaries in /opt/cni/bin. We need to make sure that directory exists before running the cp, and need to run cp in a way that doesn't result in the source directory being created in target (we only want the executables).
The /opt/libexec thing was an experiment that can be removed as well, as we found another way of dealing with volume plugins.
[ describe what reviewers need to do in order to validate this PR ]
Tested that kubeadm can create a cluster with this.
=> kubernetes: Place cni binaries in /opt/cni/bin

bake.sh, convert_torcx_image.sh, create_docker_compose_sysext.sh, create_docker_sysext.sh, create_kubernetes_sysext.sh, create_wasmtime_sysext.sh
Two somewhat unrelated changes that you may or may not care for:
1. Switch to `/usr/bin/env bash`, so that the bakery scripts can be run on Alpine (i.e., inside some Docker containers).
2. Download some Kubernetes dependencies in parallel, to be slightly faster.
The easiest way to test both changes, is to create a new Kubernetes sysext build.
I built the Kubernetes sysext on the official Alpine-based Bash image.
=> Make script runnable on Alpine, faster Kubernetes builds

bake.sh
The binaries consumed from upstream should have the same checksums already but the resulting squashfs does not because it contains the time stamps of the build.
Define the SOURCE_DATE_EPOCH variable which is enough to make mksquashfs reproducible. The user can pass an own value if there is a fixed reference time. For semantics, see
https://reproducible-builds.org/docs/source-date-epoch/
Fixes https://github.com/flatcar/sysext-bakery/issues/25
`ARCH=arm64 ./create_wasmtime_sysext.sh 4.0.0 wasmtime ; md5sum wasmtime.raw` results in the same checksum when run twice.
=> bake.sh: Set SOURCE_DATE_EPOCH if not defined

create_kubernetes_sysext.sh
The symlink for the directory in /usr/libexec has to be created like a file or otherwise it will land inside the existing directory (which shouldn't have existed).
Fix the symlink creation. A better solution would be https://github.com/flatcar/Flatcar/issues/1193 but that's for future releases.
Checked that the correct symlink is part of the image
=> Kubernetes: Correct symlink creation

create_docker_sysext.sh
This change fixes a bug with ONLY_DOCKER builds in create_docker_sysext.sh. Docker binary releases version 23 and above do not ship /usr/bin/containerd-shim anymore, leading to the following error when building a "docker only" sysext w/o containerd:
```shell
rm: cannot remove 'docker/usr/bin/containerd-shim': No such file or directory
```
This PR handles versions below major release 23 separately and only deletes containerd-shim for these versions.
Tested with docker releases 20.10.9, 23.0.0, and 24.0.6.
=> create_docker_sysext.sh: no containerd-shim in v23 and higher

.github/workflows/release.yaml
The introduced streams had different folders for each major version. There was also a bug in the match pattern.
=> .github: Share folder for streams and fix the match pattern

README.md
The Kubernetes sysext image will do major version updates which need additional work on updating. We can cover this in the Flatcar and CAPI docs but here a simpler example would be better.
=> README: Use wasmtime as simpler example

.github/workflows/release.yaml
Modify the workflow file to download information about available Kubernetes versions and build all raw images for the last maintenance release for every main release.
[ describe what reviewers need to do in order to validate this PR ]
[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]
- I created a fork of this project
- I then did the changes needed for the workflow file to create desired outcome.
- I pushed my changes to github to see if it would result in the images I want to have.
=> Build all Kubernetes versions available. Fix for https://github.com/flatcar/Flatcar/issues/1293

.github/workflows/release.yaml
To prepare the landing of Docker >= 24.0.9 in https://download.docker.com/linux/static/stable/x86_64/
Related to: https://github.com/flatcar/sysext-bakery/issues/37
=> workflow: bump docker release

.github/workflows/release.yaml, README.md, release_build.sh, release_build_versions.txt
This change updates the release GitHub Actions workflow to build a new release instead of modifying an existing one. The previous "latest" release will be deleted.
The release will contain all sysexts listed in
"release_build_versions.txt" as well as all sysexts included in the previous latest release. It will generate a Release.md to be included in the release.
The change also updates the workflow to only run when the tag "latest" is pushed.
=> release action: Create new release from list, include old release

.github/workflows/release.yaml
This is to avoid using deprecated node16.
=> .github: Bump github actions

README.md, release_build_versions.txt
As is says in the title. README.md has been updated accordingly to discuss wasmtime 17.
This PR also serves as a test for the new CI release script; retag main with "latest" after merge to trigger a release.
=> releases: update docker 25 to 25.0.3, wasmtime to 17.0.1

.github/workflows/release.yaml
The "delete tag" action step included a spurious reference to the checkout action which lead to CI breakage:
```
Error: .github#L1
a step cannot have both the `uses` and `run` keys
```
This change fixes that issue.
=> release.yaml: remove spurious checkout action to un-break CI

.github/workflows/release.yaml
This change fixes an issue with the release github action that led to the release build script not being found after check-out:
```
> Run release_build.sh
/home/runner/work/_temp/8f920e48-5134-4d40-afcc-45d61f2f9226.sh: line 1: release_build.sh: command not found
Error: Process completed with exit code 127.
```
See e.g. https://github.com/flatcar/sysext-bakery/actions/runs/7884817335/job/21514630897
=> release.yaml: fix git repo directory

release_build.sh
The wget log output is too long and the date needs to be dynamic.
Other topic: I see that an old 202309 release was used to fetch previous assets. Let's delete those.
=> release_build: Remove log output and hardcoded date

README.md, bake_flatcar_image.sh
This change introduces `bake_flatcar_image.sh`, a standalone script for creating Flatcar OS images with sysexts (from the bakery and other sources) included.
The script will download a generic Flatcar OS image (version can be specified), copy local sysexts into root or OEM partitions, and create respective symlinks to `/etc/extensions`.
By default, the script operates on local sysext files. However, the `--fetch` option may be specified to download  sysext(s) from the latest Bakery release.
Optionally, vendor images can be created. If requested, the script will use the Flatcar SDK corresponding to the OS image version to generate vendor images from the generic image.
**NOTE** that building vendor images requires https://github.com/flatcar/scripts/pull/1682 . To test, apply …
=> bake_flatcar_image.sh: Bake sysexts into Flatcar OS images

README.md, bake.sh, convert_torcx_image.sh, create_docker_sysext.sh, create_kubernetes_sysext.sh
All Flatcar channels are now on systemd 252 and can make use of ID=_any. While we don't support EXTENSION_RELOAD_MANAGER=1 yet, we should start to specify it for old images to keep working when we require it.
Loaded a resulting image on Flatcar Stable.
=> Default to ID=_any and make use of EXTENSION_RELOAD_MANAGER=1

README.md, create_wasmcloud_sysext.sh, release_build_versions.txt
This adds a new recipe for baking a [wasmCloud](https://wasmcloud.com/) sysext image.
Once the image is built, you can employ the following configuration ignition configuration (replacing `<your-repository-goes-here>` with the appropriate value) to consume it:
```yaml
---
variant: flatcar
version: 1.0.0
storage:
files:
- path: /opt/extensions/wasmcloud/wasmcloud-0.82.0-x86-64.raw
contents:
source: https://github.com/<your-repository-goes-here>/sysext-bakery/releases/download/latest/wasmcloud-0.82.0-x86-64.raw
- path: /etc/sysupdate.wasmcloud.d/wasmcloud.conf
contents:
source: https://github.com/<your-repository-goes-here>/sysext-bakery/releases/download/latest/wasmcloud.conf
links:
- target: /opt/extensions/wasmcloud/wasmcloud-0.82.0-x86-64.raw
path: /etc/extensions/wasmcloud.raw
hard: …
```
=> Add wasmCloud recipe

bake.sh
While the use of mksquashfs here happens in a way where no existing file should be there to append to, it's better to always overwrite. Since one might get a lot of warnings on btrfs systems about unknown xattrs, we can also silence these.
Created a wasmtime sysext
=> bake.sh: Add mksquashfs flags to prevent appending and reduce warnings

bake.sh
Old mksquashfs versions don't support the xattr exclusion that was added to prevent harmless warnings getting printed. To support old mksquashfs versions, gate this behind a version check.
I tested `./create_wasmtime_sysext.sh 4.0.0 wasmtime` with a 4.6 version, and for an older version it was also [tested](https://kubernetes.slack.com/archives/C03GQ8B5XNJ/p1713360007210139?thread_ts=1713355624.708779&cid=C03GQ8B5XNJ)
=> bake.sh: Gate mksquashfs xattr exclusion behind version check

create_crio_sysext.sh
=> add CRIO support

README.md, create_wasmcloud_sysext.sh, release_build_versions.txt
[wasmCloud 1.0 landed yesterday](https://wasmcloud.com/blog/wasmcloud-1.0-webassembly-apps-production-any-cloud-any-edge), so this adds that as a new build version.
Once the image is built, you can employ the following configuration ignition configuration (replacing <your-repository-goes-here> with the appropriate value) to consume it:
```yaml
---
variant: flatcar
version: 1.0.0
storage:
files:
- path: /opt/extensions/wasmcloud/wasmcloud-1.0.0-x86-64.raw
contents:
source: https://github.com/<your-repository-goes-here>/sysext-bakery/releases/download/latest/wasmcloud-1.0.0-x86-64.raw
- path: /etc/sysupdate.wasmcloud.d/wasmcloud.conf
contents:
source: https://github.com/<your-repository-goes-here>/sysext-bakery/releases/download/latest/wasmcloud.conf
links:
- target: …
```
=> Add wasmCloud 1.0

create_keepalived_sysext.sh
Add keepalived sysext
Currently there is no official container for keepalived, so this recipe builds it statically from a github tag.
It requires docker for the building process.
=> Add keepalived

README.md, create_k3s_sysext.sh
create `/usr/local/lib/systemd/system/k3s.service` and `/usr/local/lib/systemd/system/k3s-agent.service`
unit files were taken from the k3s install script at [get.k3s.io](https://get.k3s.io/).
=> create_k3s_sysext.sh: create systemd unit files

README.md, create_rke2_sysext.sh
Add a new script that builds a sysext containing the [Rancher rke2](https://github.com/rancher/rke2/) binary and its systemd units.
```bash
./create_rke2_sysext.sh v1.29.2+rke2r1 rke2-v1.29.2+rke2r1
```
This will download rke2 in version `v1.29.2+rke2r1` and create a sysext named `rke2-v1.29.2+rke2r1.raw`.
I tested the script locally and got a working sysext.
=> ADD create_rke2_sysext.sh

README.md, release_build_versions.txt
Recently more build scripts got added and not all are covered in the release yet. Add a table that gives an overview on available extensions and whether they are released or not. We try to release all extensions, I didn't do it for keepalived now because it was quite slow to build for arm64. While at it fix the README order a bit, added a Butane template and made the release instructions more robust against mistakes.
Create a new release after merge.
[Checked rendering](https://github.com/flatcar/sysext-bakery/tree/kai/overview?tab=readme-ov-file#available-extensions)
=> Add extension overview and release all repackaged extensions

create_k3s_sysext.sh
Create symlinks for kubectl, ctr and crictl, like the k3s install script does
=> create_k3s_sysext.sh: create symlinks 

README.md, flatwrap.sh, flix.sh, oci-rootfs.sh
Existing binaries can be bundled in a sysext image if they use their own library path or do what Flatpak does and run in a chroot. This introduces the Flix tool which creates sysext images from a given chroot and a set of binaries in it, and then patches the ELF rpath section and to refer to a custom library path.
The other tool introduced here is the Flatwrap tool that creates sysext images from a given chroot and a set of binaries in it, and sets up wrapper entry points with bwrap/unshare into the chroot. This also introduces a helper oci-rootfs.sh to create a useable chroot from a container image.
See README
=> flix and flatwrap: Add tools to convert a chroot to a sysext

oci-rootfs.sh
#74 added the `oci-rootfs.sh` script which automatically selects `podman` instead of `docker` when it is available on the system running the `oci-rootfs.sh` script. This PR fixes the following command in that script:
https://github.com/flatcar/sysext-bakery/blob/11280db5e80530505857385af088525d3be1675a/oci-rootfs.sh#L50
which assumes the use of `docker`, even when `podman` is used for all other commands, and which had resulted in the script quitting with an error when `podman` is selected instead of `docker` for https://github.com/flatcar/sysext-bakery/blob/11280db5e80530505857385af088525d3be1675a/oci-rootfs.sh#L53
On my computer (which is running the https://github.com/ublue-os/bluefin/pkgs/container/aurora-dx custom Fedora OS image), I attempted to run the following command:
``` …
```
=> Fix typo in command in `oci-rootfs.sh` for podman-based hosts

README.md, create_nvidia_runtime_sysext.sh, release_build_versions.txt
PoC to test building nvidia-container-toolkit as an external sysext.
=> Nvidia runtime

.github/workflows/release.yaml, create_nvidia_runtime_sysext.sh, release_build.sh
I tested the release process on a fork and there were issues:
- cri-o is missing releases for k8s 1.31 - skip
- nvidia-runtime needs to build with ubuntu 18 (not 20) because arm64 targets are missing
- needed to add cross-buildx to the workflow
- rke and k3s have '+' in filenames, this wasn't being handled correctly (asset urls contain an escape sequence)
=> Fix release_build

README.md, release_build_versions.txt
This brings wasmCloud up to date with the latest release, [v1.2.1](https://github.com/wasmCloud/wasmCloud/releases/tag/v1.2.1).
It also removes `v0.82.0`, because realistically no-one should be using that as it is not really supported or compatible with the latest the `v1.x` line of wasmCloud releases.
Once the image is built, you can employ the following configuration ignition configuration (replacing with the appropriate value) to consume it as outlined in the updated README.
I've built and deployed this on to a DigitalOcean Droplet to validate that it works as expected:
```shell
Flatcar Container Linux by Kinvolk stable 3975.2.1 for DigitalOcean
core@flatcar-sysext-01 ~ $ wasmcloud --version
wasmcloud 1.2.1
```
=> Bump wasmcloud to 1.2.1

release_build_versions.txt
v1.16.1 is affected by CVE-2024-0132 and CVE-2024-0133. See [1].
[1]: https://nvidia.custhelp.com/app/answers/detail/a_id/5582/~/security-bulletin%3A-nvidia-container-toolkit---september-2024
=> Bump nvidia-runtime version to v1.16.2

.github/workflows/release.yaml, bake_flatcar_image.sh, release_build.sh
Fix issues we have had with sysext releases. Previously upload failure would cause us to lose release assets, because the release gets deleted before upload.
=> Rework sysext release

bake.sh
The mksquashfs version that supports the xattrs-exclude flag is 4.6.1, but the logic excluded the version because of a strict (greater than) comparison.
See: https://github.com/flatcar/sysext-bakery/pull/60/commits/d1419fc1254f9723a3614811bdd29f9d6a3bba9d
[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]
=> bake: fix mksquashfs version check

README.md, release_build_versions.txt
Didn't know if you want to keep v1.30.5 and v1.29.9 for backwards-compatibility, so I kept them in `release_build_versions.txt`. If you only want to build the latest release, I can update the PR as well.
=> Bump k3s and rke2 to v1.31.1

bake_flatcar_image.sh
This change updates the list of supported vendors to the latest SDK supported vendors, including akamai and Hetzner.
Initial clean-up was improved by adding 'sudo' to remove SDK image builds if present.
=> bake_flatcar_image.sh: Update list of vendors, improve clean-up

README.md, docs/containerd.md, docs/crio.md, docs/docker.md, docs/docker_compose.md, docs/falco.md, docs/k3s.md, docs/keepalived.md, docs/kubernetes.md, docs/llamaedge.md, docs/nvidia_runtime.md, docs/ollama.md, docs/rke2.md, docs/tailscale.md, docs/wasmcloud.md, docs/wasmedge.md, docs/wasmtime.md
This change is a thorough documentation overhaul.
The main README has been refactored to provide a top-down, user-centric view of the Bakery. All specific sysexts are discussed in separate files. All sysexts now come with full-blown ready-to-use example configurations.
=> README, docs/: overhaul the bakery documentation

release_build.sh
The build script tries to fetch previous "latest" release sysexts. The `curl` command fails when the release "latest" does not exist. This is inconvenient when users want to test the pipeline in their own forks before opening PRs. 
This should be trivial to review, I guess?
With this change introduced, I successfully ran the pipeline in my fork with no existing release.
=> Fix CI workflow when creating the first release

_skel.sysext/create.sh, kubernetes.sysext/create.sh, release_build_versions.txt, wasmcloud.sysext/create.sh
This change updates release_build_versions.txt to use the correct version strings as reported by ./bakery.sh list <extension>. It also uses curl_wrapper in extensions' create.sh scripts for accessing api.github.com to avoud throttling (curl_wrapper uses GH_TOKEN for authentication if set).
=> release_build_versions.txt: use correct version strings

release_dispatcher.sh
The version variable is used as both an array and a scalar type in release_dispatcher.sh. When being set to a scalar value and previously being used as array, only the first array member is overwritten. This leads to erroneous build dispatches because versions are mixed up.
We explicitly un-set the variable at the end of the version loop
We also check the presence of <extension>:<version> pairs in the build array before adding new ones to prevent cases where "latest" and a pinned version are identical
=> release_dispatcher.sh: fix version array

README.md, docs/k3s.md, docs/kubernetes.md, docs/rke2.md, tools/http-url-rewrite-server/Caddyfile
Some extensions, e.g. Kubernetes, do not allow unattended in-place updates across major versions. These use the pattern `<extension>-<majorversion>.conf` for their sysupdate configurations.
The URL rewriter incorrectly redirects to
`.../releases/tags/<extension>-<majorversion>/<extension>-<majorversion>.conf`.
This change adds an explicit `.../<release>/<file>.(conf|raw)` to the URL rewriter and updates Kubernetes, rke2, and k3s documentation as well as the developer README.md .
Fixes #123
=> URL rewrite: support explicit release versions

README.md, _skel.sysext/create.sh, k3s.sysext/create.sh, kubernetes.sysext/create.sh, lib/helpers.sh, lib/list.sh, release_meta.sh, rke2.sysext/create.sh, wasmcloud.sysext/create.sh
This change addresses some corner cases in extension version detection and adds a few quality of life improvements:
- For listing bakery extension releases we now support a per-extension EXTENSION_VERSION_MATCH_PATTERN to address unusual versioning. This is helpful for e.g. versions like "rke2-v1.31.3+rke2r1".
- Stricter versioning match: bakery extension release versions use a stricter match pattern. This prevents false positive substring matches, e.g. "docker-compose" matched as a release version of "docker".
- The curl wrapper now supports github API response pagination. It has aptly been renamed to curl_api_wrapper.
=> lib/, release_meta.sh: address corner cases, qol improvements

tools/http-url-rewrite-server/Caddyfile
This change fixes an issue introduced by
510b5193ce659392efa51857b5e03e9b250f0287
when introducing sub-path retaining for confs and images. Images aren't really available from these sub-paths so we need to limit that feature to sysupdate confs only.
Fixes https://github.com/flatcar/sysext-bakery/issues/123 , #127 .
=> Caddyfile: support subpaths only for sysupdate confs

keepalived.sysext/create.sh
/usr/sbin is a symlink to /usr/bin on recent Flatcar releases. Sysexts shipping /usr/sbin would overwrite that symlink and sbin would contain only the contents that sysext ships.
We copy keepalived to /usr/bin and also pin the Alpine Linux release used for the build.
After merge we need to delete the keepalived releases to force a rebuild.
Fixes #131
=> keepalived: do not use /usr/sbin

docs/containerd.md, docs/crio.md, docs/docker.md, docs/docker_compose.md, docs/falco.md, docs/k3s.md, docs/keepalived.md, docs/kubernetes.md, docs/llamaedge.md, docs/nebula.md, docs/nerdctl.md, docs/nvidia_runtime.md, docs/ollama.md, docs/rke2.md, docs/tailscale.md, docs/wasmcloud.md, docs/wasmedge.md, docs/wasmtime.md, llamaedge.sysext/create.sh, release_build_versions.txt
Not all versions used in extensions' configuration snippets are available in the "new" bakery releases, and some were very outdated. This change updates configuration snippets to use more recent versions that actually exist in the bakery.
=> docs: fix configuration examples extension versions

docs/k3s.md
Putting the transfer definition file under `/etc/sysupdate.k3s.d/` results in the following error: `No transfer definitions for component 'k3s-v1.32' found.`.
This can be fixed by either putting the file under `/etc/sysupdate.k3s-v1.32.d/` or by setting `ExecStartPre=/usr/lib/systemd/systemd-sysupdate -C k3s update` instead of `ExecStartPre=/usr/lib/systemd/systemd-sysupdate -C k3s-v1.32 update` in [docs/k3s.md](https://github.com/flatcar/sysext-bakery/blob/d548304e38ed7da8fe37ba436b988dc4005ce6a4/docs/k3s.md?plain=1#L55).
This PR updates the path to the file in [docs/k3s.md](https://github.com/flatcar/sysext-bakery/blob/d548304e38ed7da8fe37ba436b988dc4005ce6a4/docs/k3s.md?plain=1#L35).
=> K3s: Fix path of transfer definition file in docs

docs/nerdctl.md
Reported by a user on Matrix. I've used curl to check that the new URL is valid.
=> docs: Add missing architecture in nerdctl filename

docs/nvidia_runtime.md
The doc examples are using _ but the release files are using -. Updating the docs to use - as that seems to be more consistent throughout.
=> fixing invalid urls for nvidia

docs/index.md
Use the correct vendor string for qemu :alien:
=> docs: fix typo in bake_flatcar_image docs

nvidia-runtime.sysext/create.sh, nvidia-runtime.sysext/files/usr/lib/systemd/system/nvidia.service.d/10-persistenced.conf, nvidia-runtime.sysext/files/usr/local/bin/_nvidia-runtime-helper
The sysext contains /opt/bin/nvidia-smi -> /usr/bin/nvidia-smi symlink. This does not play well with the prebuilt sysext, as it already ships the binaries in /usr/bin. Create the symlink dynamically, only when the prebuilt sysext is not loaded.
=> nvidia-runtime: create symlinks dynamically

docs/index.md, docs/opkssh.md, opkssh.sysext/create.sh
opkssh is a tool which enables ssh to be used with OpenID Connect allowing SSH access to be managed via identities like alice@example.com instead of long-lived SSH keys. It does not replace SSH, but instead generates SSH public keys containing PK Tokens and configures sshd to verify them. These PK Tokens contain standard [OpenID Connect ID Tokens](https://openid.net/specs/openid-connect-core-1_0.html). This protocol builds on the [OpenPubkey](https://github.com/openpubkey/openpubkey/blob/main/README.md) which adds user public keys to OpenID Connect without breaking compatibility with existing OpenID Provider.
https://github.com/openpubkey/opkssh
1. Add sysext as per doc  (ensuring you change `my.email@gmail.com` to your actual gmail address
2. Run `opkssh login google` to generate private …
=> Add opkssh sysext

docker-buildx.sysext/create.sh, docs/docker_buildx.md, docs/index.md, release_build_versions.txt
This adds the docker-buildx sysext to the repo. It is usually heavily used when running docker build/docker compose build. Currently docker compose build throws a warning that this is missing and this will fix that issue.
=> Docker buildx

CODEOWNERS
This PR updates the CODEOWNERS file to assign the appropriate specialized maintainer team (@flatcar/flatcar-integrations) for pull request reviews, addressing the manual reviewer assignment issues outlined in https://github.com/flatcar/Flatcar/issues/1791.
This ensures that reviews are directed to team members with the most relevant domain expertise.
=> Update CODEOWNERS with specialized team assignment

lib/helpers.sh, wasmedge.sysext/create.sh
WasmEdge tarball 0.15.0 and higher do not contain a WasmEdge.../ subdirectory anymore. Instead, the FS root is shipped directly.
This change fixes the wasmedge build for versions >=0.15.0 and adds helper functions to compare semvers.
Tested with local builds, both wasmedge-0.14.1 and wasmedge-0.15.0.
=> wasmedge: fix build for version 0.15.1 and higher
